DROP TABLE i23_produits;
CREATE TABLE i23_produits (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    libelle VARCHAR(30) NOT NULL,
    prix DOUBLE PRECISION NOT NULL,
    quantite INTEGER DEFAULT 0 NOT NULL
);

DROP TABLE i23_clients;
CREATE TABLE i23_clients (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    login VARCHAR(180) NOT NULL UNIQUE,
    roles CLOB NOT NULL,
    password VARCHAR(255) NOT NULL,
    nom VARCHAR(100) NOT NULL,
    prenom VARCHAR(50) NOT NULL,
    date_naissance DATE NOT NULL,
    UNIQUE(nom,prenom)
);

DROP TABLE i23_paniers;
CREATE TABLE i23_paniers (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
     produit_id INTEGER NOT NULL,
     client_id INTEGER NOT NULL,
     quantite INTEGER NOT NULL,
     CONSTRAINT FK_62571961F347EFB FOREIGN KEY (produit_id) REFERENCES i23_produits (id) ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE,
     CONSTRAINT FK_6257196119EB6921 FOREIGN KEY (client_id) REFERENCES i23_clients (id) ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE
)